### ISSUE TITLE
Request: make the pagination bar not bounce around when emojis are loading

### ISSUE THREAD

**Issue by mknadler** [willmanduffy/mojician#12]
![loading](https://cloud.githubusercontent.com/assets/3596891/17644864/5e94fecc-6161-11e6-85e8-e2284bae6004.gif)

This is more noticeable when larger emojis are scattered, as above. 

One thought on how this could be changed: having a container for the emojis that is different from the pagination bar + having that container have a min-height large enough to account for only the largest possible emojis?  Or just put the pagination on top :P

**Comment by willmanduffy** [comment]
OK I just deployed production with an attempt to fix this. I ended up going with flexbox to prevent this from happening. I may end up regretting this decision, but I had never had a chance to use it before and this seemed like a good chance to mess around with it because the stakes are so low.

Currently a bug where this caused the images to be too big in some cases but I am deploying a fix for that as I write this :D 

Let me know if there are any bad effects of using flexbox that you see! And thanks again!
